language: node_js
node_js:
- v10.15.3
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: uNN9ThXjkBo/za+HDp5xUHs8rporpsHY2kLJYVcHA3krWUaE5C0MB3HFFweTHkvbDNvRQvy4JryzHEmL0NrlQpVeLX++gsRo9Ljz/iUqhZsVWCC3LmQAV6u1DasRod39Flii+/JaieHaqCTQ3N4AsMPHuKJDNjyGcfKX+KAWHW/xaFCeUg+dXmiveBhOWfhXBpVE4L+job1fZrshgSHuHESrBW+OHLXBGhNMgybPBi1OG/k9zC+MxDHep6wjggZ2hCpKv35t7xtIqfAT95m5KJD9VjvfSSUPy7irIjDRkPZjayuKO0prPoXutoVhppiy0vD+0pTxhl4qsC+ENPTCmxu2faS1HmBoDfuV1T8+Fb/KGJTDd/1+beUiVOxDFcndkObeGGAMeXiR3HoNarufa8PkEmphGLRXtD26W6VyYov6pP9wHg4ytdq9rlfxLom2YnrvBcoNu4j8Wscvl3Fix4SrnOWhlAEX3abMoOHxQbi0GIF7GOl59yKPjpqIRVHSIly2OCz3lzMcN5fC36/HOivhwlKlxcf7Zj+eMtcCpoifRcwGoPhXDjFCdL8AN96sQLfXRacti4bdhoJuruMAl5psK2oijgT4hfuqAxd6RrNB64FO2/q+T5tkU4nbVF3RhhR86sdjWIn53wRxNRZZXQwBjdHAOfEVrJ0x4EwbM3g=
  app: elegant-wedding
  on: backend
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- npm run test
