language: node_js
node_js:
- v10.15.3
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: C6Tuay3gEhE9bI66CdrNdlFf9Nv29Jkhj2gVpl7Tcm+uSuc0eONljEYG6xcjeRzx5gVyoTmuVgEsSCcZuOCDYGgbUvoR2m5iaiUHgsohCKyNPRXHkxUq6K7TQ/oLhxfvhwnJqDpxQWBxXxvMuHKSb0IF9s54qPqPIEdfskty2okTbQserOh6onfxWO/ETe6ITCltCrBVXGuya6ZOghEbv3NQ3IiUL36fatpP/2oVZCmVvfjHbv/YVbNY/78nHz3tNHfLZatNH+0aBUU6GWKmPtrJnEFdHF8C6ZT9vkKA1iCGJLvUifWCSSHD5Fm8g7XXCempfzGtyX5IiQ4Grd2rC0FqxamXtWkzK6p05auv3oLbrmzpmeFWvjv512RRfmjr9EbyNutlkeMvwWino8US6aCf2brkTaexWyExqosNI53RaovvF91yd8Tfzn8e7WzZjFI7zysj8Sc8Rqcn14F/4/lwVFJc5N3uWjew4wNBpv48/MOuQGbnWJhrq5hNcYyb2Bs3E8GXYZ1DFL22VfqQ+ApiE35TiOHpmFXru4R8rQogywo6MViL1G708wrLj4UHQ2WwP4U38JTX7/apFpsfsR1CMP3UKxJQmxPMweLGEtkbkBDeuRrybr1FPhGSWvCFiK8jornGMjapt/VdKfg39j08qVIs1A8iNp6wN7+WjvA=
  app: elegant-wedding
  on: backend
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- npm run test
